heat_template_version: 2015-04-30

parameters:
  keypair_name:
    type: string
  flavor:
    type: string
  image:
    type: string
  private_net:
    type: string
  private_subnet:
    type: string
  security_group:
    type: string
  user_data:
    type: string
  public_net:
      type: string

resources:
  TowerServer:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: keypair_name }
      networks:
          - port: { get_resource: TowerServerPort }
      user_data: { get_param: user_data }
      user_data_format: RAW

  TowerServerPort:
    type: OS::Neutron::Port
    properties:
        network_id : { get_param: private_net }
        fixed_ips:
            - subnet_id: { get_param: private_subnet }
        security_groups: [ { get_param: security_group }]

  TowerServerFloatingIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: TowerServerPort }

outputs:
  ServerID:
    value: { get_resource: TowerServer }
  ServerFixedIP:
    value: { get_attr: [TowerServerPort, fixed_ips, 0, ip_address] }
  ServerFloatingIP:
    value: { get_attr: [TowerServerFloatingIP, floating_ip_address] }

